SUPPORTED_QUIZ_TYPES = {"MIXED", "BLANK", "DEFINITION", "KEYWORD_CHOICE", "OX"}
SUPPORTED_GENERATED_QUIZ_TYPES = {"BLANK", "DEFINITION", "KEYWORD_CHOICE", "OX"}
SUPPORTED_QUIZ_STATUSES = {"ACTIVE", "DELETED"}
SUPPORTED_QUIZ_SET_STATUSES = {"DRAFT", "SENT", "CLOSED"}
SUPPORTED_DIFFICULTIES = {"EASY", "MEDIUM", "HARD"}

MIN_OPTION_COUNT = 2
MAX_OPTION_COUNT = 6
MAX_QUESTION_LENGTH = 500
MAX_OPTION_LENGTH = 200
MAX_ANSWER_LENGTH = 200

MAX_KEYWORD_CHOICE_ANSWER_LENGTH = 30

SENTENCE_LIKE_ANSWER_MARKERS = (
    "다",
    "한다",
    "된다",
    "있다",
    "없다",
    "원한다",
    "바란다",
    "영향을미친다",
)
